// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getGroupBalance = `-- name: GetGroupBalance :many
SELECT
  u.id AS user_id,
  COALESCE(SUM(es.amount), 0)
  - COALESCE(SUM(CASE WHEN e.paid_by = u.id THEN e.amount END), 0) AS balance
FROM user_groups ug
JOIN users u ON u.id = ug.user_id
LEFT JOIN expenses e ON e.group_id = ug.group_id
LEFT JOIN expense_splits es ON e.id = es.expense_id AND es.user_id = u.id
WHERE ug.group_id = $1
GROUP BY u.id
`

type GetGroupBalanceRow struct {
	UserID  uuid.UUID
	Balance int32
}

func (q *Queries) GetGroupBalance(ctx context.Context, groupID uuid.UUID) ([]GetGroupBalanceRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupBalance, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupBalanceRow
	for rows.Next() {
		var i GetGroupBalanceRow
		if err := rows.Scan(&i.UserID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverallUserBalance = `-- name: GetOverallUserBalance :one
SELECT
  COALESCE(SUM(es.amount), 0)
  - COALESCE(SUM(CASE WHEN e.paid_by = $1 THEN e.amount END), 0) AS balance
FROM expenses e
LEFT JOIN expense_splits es
  ON e.id = es.expense_id AND es.user_id = $1
`

func (q *Queries) GetOverallUserBalance(ctx context.Context, paidBy uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getOverallUserBalance, paidBy)
	var balance int32
	err := row.Scan(&balance)
	return balance, err
}

const getUserBalanceInGroup = `-- name: GetUserBalanceInGroup :one
SELECT
  COALESCE(SUM(es.amount), 0)
  - COALESCE(SUM(CASE WHEN e.paid_by = $1 THEN e.amount END), 0) AS balance
FROM expenses e
LEFT JOIN expense_splits es
  ON e.id = es.expense_id AND es.user_id = $1
WHERE e.group_id = $2
`

type GetUserBalanceInGroupParams struct {
	PaidBy  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) GetUserBalanceInGroup(ctx context.Context, arg GetUserBalanceInGroupParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserBalanceInGroup, arg.PaidBy, arg.GroupID)
	var balance int32
	err := row.Scan(&balance)
	return balance, err
}
