// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_split.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addExpenseSplits = `-- name: AddExpenseSplits :one
INSERT INTO expense_splits (
    expense_id,
    user_id,
    amount,
    paid_to
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, expense_id, user_id, amount, created_at, updated_at, paid_to
`

type AddExpenseSplitsParams struct {
	ExpenseID uuid.UUID
	UserID    uuid.UUID
	Amount    string
	PaidTo    uuid.UUID
}

func (q *Queries) AddExpenseSplits(ctx context.Context, arg AddExpenseSplitsParams) (ExpenseSplit, error) {
	row := q.db.QueryRowContext(ctx, addExpenseSplits,
		arg.ExpenseID,
		arg.UserID,
		arg.Amount,
		arg.PaidTo,
	)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidTo,
	)
	return i, err
}

const deleteSplitsByExpenseId = `-- name: DeleteSplitsByExpenseId :exec
DELETE FROM expense_splits
WHERE expense_id = $1
`

func (q *Queries) DeleteSplitsByExpenseId(ctx context.Context, expenseID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSplitsByExpenseId, expenseID)
	return err
}

const deleteSplitsByPaidBy = `-- name: DeleteSplitsByPaidBy :exec
DELETE FROM expense_splits
WHERE expense_id = $1
  AND (user_id = $2 OR paid_to = $2)
`

type DeleteSplitsByPaidByParams struct {
	ExpenseID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteSplitsByPaidBy(ctx context.Context, arg DeleteSplitsByPaidByParams) error {
	_, err := q.db.ExecContext(ctx, deleteSplitsByPaidBy, arg.ExpenseID, arg.UserID)
	return err
}

const getSplitsByExpenseId = `-- name: GetSplitsByExpenseId :many
SELECT id, expense_id, user_id, amount, created_at, updated_at, paid_to FROM expense_splits 
WHERE expense_id = $1
`

func (q *Queries) GetSplitsByExpenseId(ctx context.Context, expenseID uuid.UUID) ([]ExpenseSplit, error) {
	rows, err := q.db.QueryContext(ctx, getSplitsByExpenseId, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseSplit
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSplitsByUserId = `-- name: GetSplitsByUserId :many
SELECT id, expense_id, user_id, amount, created_at, updated_at, paid_to FROM expense_splits 
WHERE user_id = $1
`

func (q *Queries) GetSplitsByUserId(ctx context.Context, userID uuid.UUID) ([]ExpenseSplit, error) {
	rows, err := q.db.QueryContext(ctx, getSplitsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseSplit
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateSplitTotalEqualsExpense = `-- name: ValidateSplitTotalEqualsExpense :one
SELECT 1
FROM expenses e
WHERE e.id = $1 AND e.amount = (
    SELECT COALESCE(SUM(es.amount), 0)
    FROM expense_splits es
    WHERE es.expense_id = e.id
)
`

func (q *Queries) ValidateSplitTotalEqualsExpense(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateSplitTotalEqualsExpense, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
