// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    group_id,
    paid_by,
    amount,
    description,
    created_at,
    paid
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, paid_by, description, amount, paid, created_at, updated_at
`

type CreateExpenseParams struct {
	GroupID     uuid.UUID
	PaidBy      uuid.UUID
	Amount      string
	Description sql.NullString
	CreatedAt   time.Time
	Paid        bool
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.GroupID,
		arg.PaidBy,
		arg.Amount,
		arg.Description,
		arg.CreatedAt,
		arg.Paid,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PaidBy,
		&i.Description,
		&i.Amount,
		&i.Paid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :one
DELETE FROM expenses WHERE id = $1 
RETURNING id, group_id, paid_by, description, amount, paid, created_at, updated_at
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRowContext(ctx, deleteExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PaidBy,
		&i.Description,
		&i.Amount,
		&i.Paid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseById = `-- name: GetExpenseById :one
SELECT id, group_id, paid_by, description, amount, paid, created_at, updated_at FROM expenses WHERE id = $1
`

func (q *Queries) GetExpenseById(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseById, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PaidBy,
		&i.Description,
		&i.Amount,
		&i.Paid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenses = `-- name: GetExpenses :many
SELECT id, group_id, paid_by, description, amount, paid, created_at, updated_at FROM expenses
`

func (q *Queries) GetExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PaidBy,
			&i.Description,
			&i.Amount,
			&i.Paid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByGroupId = `-- name: GetExpensesByGroupId :many
SELECT id, group_id, paid_by, description, amount, paid, created_at, updated_at FROM expenses WHERE group_id = $1
`

func (q *Queries) GetExpensesByGroupId(ctx context.Context, groupID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByGroupId, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PaidBy,
			&i.Description,
			&i.Amount,
			&i.Paid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByUserId = `-- name: GetExpensesByUserId :many
SELECT id, group_id, paid_by, description, amount, paid, created_at, updated_at FROM expenses WHERE paid_by = $1
`

func (q *Queries) GetExpensesByUserId(ctx context.Context, paidBy uuid.UUID) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByUserId, paidBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PaidBy,
			&i.Description,
			&i.Amount,
			&i.Paid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses SET
    amount = COALESCE($2, amount),
    description = COALESCE($3, description),
    paid = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, group_id, paid_by, description, amount, paid, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID          uuid.UUID
	Amount      string
	Description sql.NullString
	Paid        bool
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.Paid,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PaidBy,
		&i.Description,
		&i.Amount,
		&i.Paid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validateExpenseExists = `-- name: ValidateExpenseExists :one
SELECT 1 FROM expenses WHERE id = $1
`

func (q *Queries) ValidateExpenseExists(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateExpenseExists, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const validateExpenseUserIsGroupMember = `-- name: ValidateExpenseUserIsGroupMember :one
SELECT 1
FROM user_groups ug
WHERE ug.user_id = $1 AND ug.group_id = $2
LIMIT 1
`

type ValidateExpenseUserIsGroupMemberParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) ValidateExpenseUserIsGroupMember(ctx context.Context, arg ValidateExpenseUserIsGroupMemberParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateExpenseUserIsGroupMember, arg.UserID, arg.GroupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const validateUserIsExpenseOwner = `-- name: ValidateUserIsExpenseOwner :one
SELECT 1
FROM expenses
WHERE id = $1 AND paid_by = $2
`

type ValidateUserIsExpenseOwnerParams struct {
	ID     uuid.UUID
	PaidBy uuid.UUID
}

func (q *Queries) ValidateUserIsExpenseOwner(ctx context.Context, arg ValidateUserIsExpenseOwnerParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateUserIsExpenseOwner, arg.ID, arg.PaidBy)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
