// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Expense struct {
	ID          uuid.UUID
	GroupID     uuid.UUID
	PaidBy      uuid.UUID
	Description sql.NullString
	Amount      string
	Paid        bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ExpenseSplit struct {
	ID        uuid.UUID
	ExpenseID uuid.UUID
	UserID    uuid.UUID
	Amount    string
	CreatedAt time.Time
	UpdatedAt time.Time
	PaidTo    uuid.UUID
}

type Friend struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FriendID  uuid.UUID
	Status    string
	CreatedAt time.Time
}

type Group struct {
	ID          uuid.UUID
	GroupName   string
	Description sql.NullString
	TotalAmount string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID          uuid.UUID
	FirebaseUid string
	UserName    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UserDetail struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserGroup struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GroupID   uuid.UUID
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
