// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_groups (user_id, group_id) VALUES ($1, $2)
`

type AddUserToGroupParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.UserID, arg.GroupID)
	return err
}

const checkUserExistsByEmail = `-- name: CheckUserExistsByEmail :one
SELECT 1 FROM user_details WHERE email = $1 LIMIT 1
`

func (q *Queries) CheckUserExistsByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkUserExistsByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    firebase_uid,
    role
) VALUES (
    $1,
    $2
)
RETURNING id, firebase_uid, role, created_at, updated_at
`

type CreateUserParams struct {
	FirebaseUid string
	Role        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FirebaseUid, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserById, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.firebase_uid, u.role, u.created_at, u.updated_at, ud.user_name, ud.email
FROM users u
JOIN user_details ud ON u.id = ud.user_id
WHERE ud.email = $1
`

type GetUserByEmailRow struct {
	ID          uuid.UUID
	FirebaseUid string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserName    string
	Email       string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
	)
	return i, err
}

const getUserByFirebaseUid = `-- name: GetUserByFirebaseUid :one
SELECT id, firebase_uid, role, created_at, updated_at FROM users WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUid(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirebaseUid, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, firebase_uid, role, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT u.id, u.firebase_uid, u.role, u.created_at, u.updated_at, ud.user_name, ud.email
FROM users u
JOIN user_details ud ON u.id = ud.user_id
WHERE ud.user_name = $1
`

type GetUserByNameRow struct {
	ID          uuid.UUID
	FirebaseUid string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserName    string
	Email       string
}

func (q *Queries) GetUserByName(ctx context.Context, userName string) (GetUserByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, userName)
	var i GetUserByNameRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
	)
	return i, err
}

const getUserExpensesByUserId = `-- name: GetUserExpensesByUserId :many
SELECT e.id, e.group_id, e.paid_by, e.description, e.amount, e.created_at, e.updated_at
FROM expenses e
WHERE e.paid_by = $1
`

func (q *Queries) GetUserExpensesByUserId(ctx context.Context, paidBy uuid.UUID) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getUserExpensesByUserId, paidBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PaidBy,
			&i.Description,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT ug.id, ug.user_id, ug.group_id, ug.role, ug.created_at, ug.updated_at, g.group_name, g.description
FROM user_groups ug 
JOIN groups g ON ug.group_id = g.id
WHERE ug.user_id = $1
`

type GetUserGroupsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	GroupID     uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	GroupName   string
	Description sql.NullString
}

func (q *Queries) GetUserGroups(ctx context.Context, userID uuid.UUID) ([]GetUserGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGroupsRow
	for rows.Next() {
		var i GetUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSettlements = `-- name: GetUserSettlements :many
SELECT s.id, s.group_id, s.from_user_id, s.to_user_id, s.amount, s.created_at
FROM settlements s
WHERE s.from_user_id = $1 OR s.to_user_id = $1
`

func (q *Queries) GetUserSettlements(ctx context.Context, fromUserID uuid.UUID) ([]Settlement, error) {
	rows, err := q.db.QueryContext(ctx, getUserSettlements, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Settlement
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithDetails = `-- name: GetUserWithDetails :one
SELECT u.id, u.firebase_uid, u.role, u.created_at, u.updated_at, ud.user_name, ud.email
FROM users u
JOIN user_details ud ON ud.user_id = u.id
WHERE u.id = $1
`

type GetUserWithDetailsRow struct {
	ID          uuid.UUID
	FirebaseUid string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserName    string
	Email       string
}

func (q *Queries) GetUserWithDetails(ctx context.Context, id uuid.UUID) (GetUserWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithDetails, id)
	var i GetUserWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, firebase_uid, role, created_at, updated_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, firebase_uid, role, created_at, updated_at FROM users WHERE role = $1
`

func (q *Queries) GetUsersByRole(ctx context.Context, role string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM user_groups WHERE user_id = $1 AND group_id = $2
`

type RemoveUserFromGroupParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    role = COALESCE($2, role),
    updated_at = now()
WHERE id = $1
RETURNING id, firebase_uid, role, created_at, updated_at
`

type UpdateUserParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validateUserExists = `-- name: ValidateUserExists :one
SELECT 1 FROM users WHERE id = $1
`

func (q *Queries) ValidateUserExists(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateUserExists, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
