// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_details.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserDetails = `-- name: CreateUserDetails :one
INSERT INTO user_details (user_id, user_name, email)
VALUES ($1, $2, $3)
RETURNING id, user_id, user_name, email, created_at, updated_at
`

type CreateUserDetailsParams struct {
	UserID   uuid.UUID
	UserName string
	Email    string
}

func (q *Queries) CreateUserDetails(ctx context.Context, arg CreateUserDetailsParams) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, createUserDetails, arg.UserID, arg.UserName, arg.Email)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetailsByEmail = `-- name: GetUserDetailsByEmail :one
SELECT id, user_id, user_name, email, created_at, updated_at
FROM user_details
WHERE email = $1
`

func (q *Queries) GetUserDetailsByEmail(ctx context.Context, email string) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, getUserDetailsByEmail, email)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetailsByUserId = `-- name: GetUserDetailsByUserId :one
SELECT user_details.id, user_id, user_name, email, user_details.created_at, user_details.updated_at, users.id, firebase_uid, role, users.created_at, users.updated_at
FROM user_details
JOIN users ON user_details.user_id = users.id
WHERE user_details.user_id = $1
`

type GetUserDetailsByUserIdRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	UserName    string
	Email       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ID_2        uuid.UUID
	FirebaseUid string
	Role        string
	CreatedAt_2 time.Time
	UpdatedAt_2 time.Time
}

func (q *Queries) GetUserDetailsByUserId(ctx context.Context, userID uuid.UUID) (GetUserDetailsByUserIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserDetailsByUserId, userID)
	var i GetUserDetailsByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.FirebaseUid,
		&i.Role,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const updateUserDetails = `-- name: UpdateUserDetails :one
UPDATE user_details
SET user_name = COALESCE($2, user_name),
    email = COALESCE($3, email),
    updated_at = now()
WHERE user_id = $1
RETURNING id, user_id, user_name, email, created_at, updated_at
`

type UpdateUserDetailsParams struct {
	UserID   uuid.UUID
	UserName string
	Email    string
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, updateUserDetails, arg.UserID, arg.UserName, arg.Email)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
