// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkUserInGroup = `-- name: CheckUserInGroup :one
SELECT 1
FROM user_groups
WHERE user_id = $1
  AND group_id = $2
`

type CheckUserInGroupParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) CheckUserInGroup(ctx context.Context, arg CheckUserInGroupParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkUserInGroup, arg.UserID, arg.GroupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUserIsGroupAdmin = `-- name: CheckUserIsGroupAdmin :one
SELECT 1
FROM user_groups
WHERE user_id = $1
  AND group_id = $2
  AND role = 'admin'
`

type CheckUserIsGroupAdminParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) CheckUserIsGroupAdmin(ctx context.Context, arg CheckUserIsGroupAdminParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkUserIsGroupAdmin, arg.UserID, arg.GroupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    group_name,
    description
) VALUES (
    $1,
    $2
)
RETURNING id, group_name, description, total_amount, created_at, updated_at
`

type CreateGroupParams struct {
	GroupName   string
	Description sql.NullString
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.GroupName, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Description,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupById = `-- name: DeleteGroupById :one
DELETE FROM groups
WHERE id = $1
RETURNING id, group_name, description, total_amount, created_at, updated_at
`

func (q *Queries) DeleteGroupById(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, deleteGroupById, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Description,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupAdmins = `-- name: GetGroupAdmins :many
SELECT u.id, u.firebase_uid, u.role, u.created_at, u.updated_at
FROM users u
JOIN user_groups ug ON u.id = ug.user_id
WHERE ug.group_id = $1
  AND ug.role = 'admin'
`

func (q *Queries) GetGroupAdmins(ctx context.Context, groupID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getGroupAdmins, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupById = `-- name: GetGroupById :one
SELECT id, group_name, description, total_amount, created_at, updated_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupById(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupById, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Description,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, group_name, description, total_amount, created_at, updated_at
FROM groups
WHERE group_name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, groupName string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, groupName)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Description,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT u.id, u.firebase_uid, u.role, u.created_at, u.updated_at
FROM users u
JOIN user_groups ug ON u.id = ug.user_id
WHERE ug.group_id = $1
`

func (q *Queries) GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroups = `-- name: GetGroups :many
SELECT id, group_name, description, total_amount, created_at, updated_at
FROM groups
`

func (q *Queries) GetGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.Description,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByUserId = `-- name: GetGroupsByUserId :many
SELECT g.id, g.group_name, g.description, g.total_amount, g.created_at, g.updated_at
FROM groups g
JOIN user_groups ug ON g.id = ug.group_id
WHERE ug.user_id = $1
`

func (q *Queries) GetGroupsByUserId(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.Description,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleInGroup = `-- name: GetUserRoleInGroup :one
SELECT role
FROM user_groups
WHERE user_id = $1 AND group_id = $2
`

type GetUserRoleInGroupParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) GetUserRoleInGroup(ctx context.Context, arg GetUserRoleInGroupParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleInGroup, arg.UserID, arg.GroupID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    group_name = COALESCE($2, group_name),
    description = COALESCE($3, description),
    updated_at = now()
WHERE id = $1
RETURNING id, group_name, description, total_amount, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          uuid.UUID
	GroupName   string
	Description sql.NullString
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup, arg.ID, arg.GroupName, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Description,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validateGroupExists = `-- name: ValidateGroupExists :one
SELECT 1
FROM groups
WHERE id = $1
`

func (q *Queries) ValidateGroupExists(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateGroupExists, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
