// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settlements.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addSettlement = `-- name: AddSettlement :one
INSERT INTO settlements (
    group_id,
    from_user_id,
    to_user_id,
    amount
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, group_id, from_user_id, to_user_id, amount, created_at
`

type AddSettlementParams struct {
	GroupID    uuid.UUID
	FromUserID uuid.UUID
	ToUserID   uuid.UUID
	Amount     string
}

func (q *Queries) AddSettlement(ctx context.Context, arg AddSettlementParams) (Settlement, error) {
	row := q.db.QueryRowContext(ctx, addSettlement,
		arg.GroupID,
		arg.FromUserID,
		arg.ToUserID,
		arg.Amount,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSettlementById = `-- name: DeleteSettlementById :one
DELETE FROM settlements WHERE id=$1 RETURNING id, group_id, from_user_id, to_user_id, amount, created_at
`

func (q *Queries) DeleteSettlementById(ctx context.Context, id uuid.UUID) (Settlement, error) {
	row := q.db.QueryRowContext(ctx, deleteSettlementById, id)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getSettlementById = `-- name: GetSettlementById :one
SELECT id, group_id, from_user_id, to_user_id, amount, created_at FROM settlements WHERE id = $1
`

func (q *Queries) GetSettlementById(ctx context.Context, id uuid.UUID) (Settlement, error) {
	row := q.db.QueryRowContext(ctx, getSettlementById, id)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getSettlementsByGroupId = `-- name: GetSettlementsByGroupId :many
SELECT id, group_id, from_user_id, to_user_id, amount, created_at FROM settlements WHERE group_id = $1
`

func (q *Queries) GetSettlementsByGroupId(ctx context.Context, groupID uuid.UUID) ([]Settlement, error) {
	rows, err := q.db.QueryContext(ctx, getSettlementsByGroupId, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Settlement
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettlementsByUserId = `-- name: GetSettlementsByUserId :many
SELECT id, group_id, from_user_id, to_user_id, amount, created_at FROM settlements
WHERE from_user_id = $1 
    OR to_user_id = $1
`

func (q *Queries) GetSettlementsByUserId(ctx context.Context, fromUserID uuid.UUID) ([]Settlement, error) {
	rows, err := q.db.QueryContext(ctx, getSettlementsByUserId, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Settlement
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateUsersInSameGroup = `-- name: ValidateUsersInSameGroup :one
SELECT 1
FROM user_groups
WHERE group_id = $3
    AND user_id IN ($1, $2)
GROUP BY group_id
HAVING COUNT(DISTINCT user_id) = 2
`

type ValidateUsersInSameGroupParams struct {
	UserID   uuid.UUID
	UserID_2 uuid.UUID
	GroupID  uuid.UUID
}

func (q *Queries) ValidateUsersInSameGroup(ctx context.Context, arg ValidateUsersInSameGroupParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateUsersInSameGroup, arg.UserID, arg.UserID_2, arg.GroupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
