// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_details.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserDetails = `-- name: CreateUserDetails :one
INSERT INTO user_details (user_id, user_name, email)
VALUES ($1, $2, $3)
RETURNING id, user_id, user_name, email, created_at, updated_at
`

type CreateUserDetailsParams struct {
	UserID   uuid.UUID
	UserName string
	Email    string
}

func (q *Queries) CreateUserDetails(ctx context.Context, arg CreateUserDetailsParams) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, createUserDetails, arg.UserID, arg.UserName, arg.Email)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetailsByEmail = `-- name: GetUserDetailsByEmail :one
SELECT id, user_id, user_name, email, created_at, updated_at
FROM user_details
WHERE email = $1
`

func (q *Queries) GetUserDetailsByEmail(ctx context.Context, email string) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, getUserDetailsByEmail, email)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetailsByUserId = `-- name: GetUserDetailsByUserId :one
SELECT id, user_id, user_name, email, created_at, updated_at
FROM user_details
WHERE user_id = $1
`

func (q *Queries) GetUserDetailsByUserId(ctx context.Context, userID uuid.UUID) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, getUserDetailsByUserId, userID)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDetails = `-- name: UpdateUserDetails :one
UPDATE user_details
SET user_name = COALESCE($2, user_name),
    email = COALESCE($3, email),
    updated_at = now()
WHERE user_id = $1
RETURNING id, user_id, user_name, email, created_at, updated_at
`

type UpdateUserDetailsParams struct {
	UserID   uuid.UUID
	UserName string
	Email    string
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, updateUserDetails, arg.UserID, arg.UserName, arg.Email)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
